package com.jbuild4d.base.dbaccess.dbentities.files;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.jbuild4d.base.dbaccess.anno.DBKeyField;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb4d_file_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class FileInfoEntity {
    //FILE_ID
    @DBKeyField
    private String fileId;

    //FILE_CREATE_TIME
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date fileCreateTime;

    //FILE_CREATER
    private String fileCreater;

    //FILE_NAME
    private String fileName;

    //FILE_SIZE
    private Long fileSize;

    //FILE_STORE_TYPE
    private String fileStoreType;

    //FILE_STORE_PATH
    private String fileStorePath;

    //FILE_STORE_NAME
    private String fileStoreName;

    //FILE_ORGAN_ID
    private String fileOrganId;

    //FILE_ORGAN_NAME
    private String fileOrganName;

    //FILE_EXTENSION
    private String fileExtension;

    //FILE_DESCRIPTION
    private String fileDescription;

    //FILE_READTIME
    private Integer fileReadtime;

    //FILE_STATUS
    private String fileStatus;

    public FileInfoEntity(String fileId, Date fileCreateTime, String fileCreater, String fileName, Long fileSize, String fileStoreType, String fileStorePath, String fileStoreName, String fileOrganId, String fileOrganName, String fileExtension, String fileDescription, Integer fileReadtime, String fileStatus) {
        this.fileId = fileId;
        this.fileCreateTime = fileCreateTime;
        this.fileCreater = fileCreater;
        this.fileName = fileName;
        this.fileSize = fileSize;
        this.fileStoreType = fileStoreType;
        this.fileStorePath = fileStorePath;
        this.fileStoreName = fileStoreName;
        this.fileOrganId = fileOrganId;
        this.fileOrganName = fileOrganName;
        this.fileExtension = fileExtension;
        this.fileDescription = fileDescription;
        this.fileReadtime = fileReadtime;
        this.fileStatus = fileStatus;
    }

    public FileInfoEntity() {
        super();
    }

    public String getFileId() {
        return fileId;
    }

    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    public Date getFileCreateTime() {
        return fileCreateTime;
    }

    public void setFileCreateTime(Date fileCreateTime) {
        this.fileCreateTime = fileCreateTime;
    }

    public String getFileCreater() {
        return fileCreater;
    }

    public void setFileCreater(String fileCreater) {
        this.fileCreater = fileCreater == null ? null : fileCreater.trim();
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    public Long getFileSize() {
        return fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    public String getFileStoreType() {
        return fileStoreType;
    }

    public void setFileStoreType(String fileStoreType) {
        this.fileStoreType = fileStoreType == null ? null : fileStoreType.trim();
    }

    public String getFileStorePath() {
        return fileStorePath;
    }

    public void setFileStorePath(String fileStorePath) {
        this.fileStorePath = fileStorePath == null ? null : fileStorePath.trim();
    }

    public String getFileStoreName() {
        return fileStoreName;
    }

    public void setFileStoreName(String fileStoreName) {
        this.fileStoreName = fileStoreName == null ? null : fileStoreName.trim();
    }

    public String getFileOrganId() {
        return fileOrganId;
    }

    public void setFileOrganId(String fileOrganId) {
        this.fileOrganId = fileOrganId == null ? null : fileOrganId.trim();
    }

    public String getFileOrganName() {
        return fileOrganName;
    }

    public void setFileOrganName(String fileOrganName) {
        this.fileOrganName = fileOrganName == null ? null : fileOrganName.trim();
    }

    public String getFileExtension() {
        return fileExtension;
    }

    public void setFileExtension(String fileExtension) {
        this.fileExtension = fileExtension == null ? null : fileExtension.trim();
    }

    public String getFileDescription() {
        return fileDescription;
    }

    public void setFileDescription(String fileDescription) {
        this.fileDescription = fileDescription == null ? null : fileDescription.trim();
    }

    public Integer getFileReadtime() {
        return fileReadtime;
    }

    public void setFileReadtime(Integer fileReadtime) {
        this.fileReadtime = fileReadtime;
    }

    public String getFileStatus() {
        return fileStatus;
    }

    public void setFileStatus(String fileStatus) {
        this.fileStatus = fileStatus == null ? null : fileStatus.trim();
    }
}