package com.jbuild4d.base.dbaccess.dbentities.files;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.jbuild4d.base.dbaccess.anno.DBKeyField;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb4d_file_content
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class FileContentEntity {
    //FILE_ID
    @DBKeyField
    private String fileId;

    //FILE_CONTENT
    private byte[] fileContent;

    public FileContentEntity(String fileId) {
        this.fileId = fileId;
    }

    public FileContentEntity(String fileId, byte[] fileContent) {
        this.fileId = fileId;
        this.fileContent = fileContent;
    }

    public FileContentEntity() {
        super();
    }

    public String getFileId() {
        return fileId;
    }

    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    public byte[] getFileContent() {
        return fileContent;
    }

    public void setFileContent(byte[] fileContent) {
        this.fileContent = fileContent;
    }
}