package com.jbuild4d.base.dbaccess.dbentities.files;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.jbuild4d.base.dbaccess.anno.DBKeyField;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb4d_file_ref
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class FileRefEntity {
    //REF_ID
    @DBKeyField
    private String refId;

    //REF_FILE_ID
    private String refFileId;

    //REF_OBJ_ID
    private String refObjId;

    //REF_ORDER_NUM
    private Integer refOrderNum;

    public FileRefEntity(String refId, String refFileId, String refObjId, Integer refOrderNum) {
        this.refId = refId;
        this.refFileId = refFileId;
        this.refObjId = refObjId;
        this.refOrderNum = refOrderNum;
    }

    public FileRefEntity() {
        super();
    }

    public String getRefId() {
        return refId;
    }

    public void setRefId(String refId) {
        this.refId = refId == null ? null : refId.trim();
    }

    public String getRefFileId() {
        return refFileId;
    }

    public void setRefFileId(String refFileId) {
        this.refFileId = refFileId == null ? null : refFileId.trim();
    }

    public String getRefObjId() {
        return refObjId;
    }

    public void setRefObjId(String refObjId) {
        this.refObjId = refObjId == null ? null : refObjId.trim();
    }

    public Integer getRefOrderNum() {
        return refOrderNum;
    }

    public void setRefOrderNum(Integer refOrderNum) {
        this.refOrderNum = refOrderNum;
    }
}