package com.jbuild4d.base.dbaccess.dbentities;

import com.jbuild4d.base.dbaccess.anno.DBKeyField;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TB4D_DATASET_COLUMN
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class DatasetColumnEntity {
    //COLUMN_ID
    @DBKeyField
    private String columnId;

    //COLUMN_DS_ID
    private String columnDsId;

    //COLUMN_CAPTION
    private String columnCaption;

    //COLUMN_NAME
    private String columnName;

    //COLUMN_CREATE_TIME
    private Date columnCreateTime;

    //COLUMN_CREATER
    private String columnCreater;

    //COLUMN_UPDATE_TIME
    private Date columnUpdateTime;

    //COLUMN_UPDATER
    private String columnUpdater;

    //COLUMN_DESC
    private String columnDesc;

    //COLUMN_DEFAULT_TYPE
    private String columnDefaultType;

    //COLUMN_DEFAULT_VALUE
    private String columnDefaultValue;

    //COLUMN_DEFAULT_TEXT
    private String columnDefaultText;

    //COLUMN_ORDER_NUM
    private Integer columnOrderNum;

    //COLUMN_TABLE_NAME
    private String columnTableName;

    //COLUMN_IS_CUSTOM
    private String columnIsCustom;

    public DatasetColumnEntity(String columnId, String columnDsId, String columnCaption, String columnName, Date columnCreateTime, String columnCreater, Date columnUpdateTime, String columnUpdater, String columnDesc, String columnDefaultType, String columnDefaultValue, String columnDefaultText, Integer columnOrderNum, String columnTableName, String columnIsCustom) {
        this.columnId = columnId;
        this.columnDsId = columnDsId;
        this.columnCaption = columnCaption;
        this.columnName = columnName;
        this.columnCreateTime = columnCreateTime;
        this.columnCreater = columnCreater;
        this.columnUpdateTime = columnUpdateTime;
        this.columnUpdater = columnUpdater;
        this.columnDesc = columnDesc;
        this.columnDefaultType = columnDefaultType;
        this.columnDefaultValue = columnDefaultValue;
        this.columnDefaultText = columnDefaultText;
        this.columnOrderNum = columnOrderNum;
        this.columnTableName = columnTableName;
        this.columnIsCustom = columnIsCustom;
    }

    public DatasetColumnEntity() {
        super();
    }

    public String getColumnId() {
        return columnId;
    }

    public void setColumnId(String columnId) {
        this.columnId = columnId == null ? null : columnId.trim();
    }

    public String getColumnDsId() {
        return columnDsId;
    }

    public void setColumnDsId(String columnDsId) {
        this.columnDsId = columnDsId == null ? null : columnDsId.trim();
    }

    public String getColumnCaption() {
        return columnCaption;
    }

    public void setColumnCaption(String columnCaption) {
        this.columnCaption = columnCaption == null ? null : columnCaption.trim();
    }

    public String getColumnName() {
        return columnName;
    }

    public void setColumnName(String columnName) {
        this.columnName = columnName == null ? null : columnName.trim();
    }

    public Date getColumnCreateTime() {
        return columnCreateTime;
    }

    public void setColumnCreateTime(Date columnCreateTime) {
        this.columnCreateTime = columnCreateTime;
    }

    public String getColumnCreater() {
        return columnCreater;
    }

    public void setColumnCreater(String columnCreater) {
        this.columnCreater = columnCreater == null ? null : columnCreater.trim();
    }

    public Date getColumnUpdateTime() {
        return columnUpdateTime;
    }

    public void setColumnUpdateTime(Date columnUpdateTime) {
        this.columnUpdateTime = columnUpdateTime;
    }

    public String getColumnUpdater() {
        return columnUpdater;
    }

    public void setColumnUpdater(String columnUpdater) {
        this.columnUpdater = columnUpdater == null ? null : columnUpdater.trim();
    }

    public String getColumnDesc() {
        return columnDesc;
    }

    public void setColumnDesc(String columnDesc) {
        this.columnDesc = columnDesc == null ? null : columnDesc.trim();
    }

    public String getColumnDefaultType() {
        return columnDefaultType;
    }

    public void setColumnDefaultType(String columnDefaultType) {
        this.columnDefaultType = columnDefaultType == null ? null : columnDefaultType.trim();
    }

    public String getColumnDefaultValue() {
        return columnDefaultValue;
    }

    public void setColumnDefaultValue(String columnDefaultValue) {
        this.columnDefaultValue = columnDefaultValue == null ? null : columnDefaultValue.trim();
    }

    public String getColumnDefaultText() {
        return columnDefaultText;
    }

    public void setColumnDefaultText(String columnDefaultText) {
        this.columnDefaultText = columnDefaultText == null ? null : columnDefaultText.trim();
    }

    public Integer getColumnOrderNum() {
        return columnOrderNum;
    }

    public void setColumnOrderNum(Integer columnOrderNum) {
        this.columnOrderNum = columnOrderNum;
    }

    public String getColumnTableName() {
        return columnTableName;
    }

    public void setColumnTableName(String columnTableName) {
        this.columnTableName = columnTableName == null ? null : columnTableName.trim();
    }

    public String getColumnIsCustom() {
        return columnIsCustom;
    }

    public void setColumnIsCustom(String columnIsCustom) {
        this.columnIsCustom = columnIsCustom == null ? null : columnIsCustom.trim();
    }
}