package com.jbuild4d.base.dbaccess.dbentities.builder;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.jbuild4d.base.dbaccess.anno.DBKeyField;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TB4D_DATASET_GROUP
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class DatasetGroupEntity {
    //DS_GROUP_ID
    @DBKeyField
    private String dsGroupId;

    //DS_GROUP_VALUE
    private String dsGroupValue;

    //DS_GROUP_TEXT
    private String dsGroupText;

    //DS_GROUP_ORDER_NUM
    private Integer dsGroupOrderNum;

    //DS_GROUP_CREATE_TIME
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date dsGroupCreateTime;

    //DS_GROUP_DESC
    private String dsGroupDesc;

    //DS_GROUP_STATUS
    private String dsGroupStatus;

    //DS_GROUP_PARENT_ID
    private String dsGroupParentId;

    //DS_GROUP_ISSYSTEM
    private String dsGroupIssystem;

    //DS_GROUP_DEL_ENABLE
    private String dsGroupDelEnable;

    //DS_GROUP_PID_LIST
    private String dsGroupPidList;

    //DS_GROUP_CHILD_COUNT
    private Integer dsGroupChildCount;

    public DatasetGroupEntity(String dsGroupId, String dsGroupValue, String dsGroupText, Integer dsGroupOrderNum, Date dsGroupCreateTime, String dsGroupDesc, String dsGroupStatus, String dsGroupParentId, String dsGroupIssystem, String dsGroupDelEnable, String dsGroupPidList, Integer dsGroupChildCount) {
        this.dsGroupId = dsGroupId;
        this.dsGroupValue = dsGroupValue;
        this.dsGroupText = dsGroupText;
        this.dsGroupOrderNum = dsGroupOrderNum;
        this.dsGroupCreateTime = dsGroupCreateTime;
        this.dsGroupDesc = dsGroupDesc;
        this.dsGroupStatus = dsGroupStatus;
        this.dsGroupParentId = dsGroupParentId;
        this.dsGroupIssystem = dsGroupIssystem;
        this.dsGroupDelEnable = dsGroupDelEnable;
        this.dsGroupPidList = dsGroupPidList;
        this.dsGroupChildCount = dsGroupChildCount;
    }

    public DatasetGroupEntity() {
        super();
    }

    public String getDsGroupId() {
        return dsGroupId;
    }

    public void setDsGroupId(String dsGroupId) {
        this.dsGroupId = dsGroupId == null ? null : dsGroupId.trim();
    }

    public String getDsGroupValue() {
        return dsGroupValue;
    }

    public void setDsGroupValue(String dsGroupValue) {
        this.dsGroupValue = dsGroupValue == null ? null : dsGroupValue.trim();
    }

    public String getDsGroupText() {
        return dsGroupText;
    }

    public void setDsGroupText(String dsGroupText) {
        this.dsGroupText = dsGroupText == null ? null : dsGroupText.trim();
    }

    public Integer getDsGroupOrderNum() {
        return dsGroupOrderNum;
    }

    public void setDsGroupOrderNum(Integer dsGroupOrderNum) {
        this.dsGroupOrderNum = dsGroupOrderNum;
    }

    public Date getDsGroupCreateTime() {
        return dsGroupCreateTime;
    }

    public void setDsGroupCreateTime(Date dsGroupCreateTime) {
        this.dsGroupCreateTime = dsGroupCreateTime;
    }

    public String getDsGroupDesc() {
        return dsGroupDesc;
    }

    public void setDsGroupDesc(String dsGroupDesc) {
        this.dsGroupDesc = dsGroupDesc == null ? null : dsGroupDesc.trim();
    }

    public String getDsGroupStatus() {
        return dsGroupStatus;
    }

    public void setDsGroupStatus(String dsGroupStatus) {
        this.dsGroupStatus = dsGroupStatus == null ? null : dsGroupStatus.trim();
    }

    public String getDsGroupParentId() {
        return dsGroupParentId;
    }

    public void setDsGroupParentId(String dsGroupParentId) {
        this.dsGroupParentId = dsGroupParentId == null ? null : dsGroupParentId.trim();
    }

    public String getDsGroupIssystem() {
        return dsGroupIssystem;
    }

    public void setDsGroupIssystem(String dsGroupIssystem) {
        this.dsGroupIssystem = dsGroupIssystem == null ? null : dsGroupIssystem.trim();
    }

    public String getDsGroupDelEnable() {
        return dsGroupDelEnable;
    }

    public void setDsGroupDelEnable(String dsGroupDelEnable) {
        this.dsGroupDelEnable = dsGroupDelEnable == null ? null : dsGroupDelEnable.trim();
    }

    public String getDsGroupPidList() {
        return dsGroupPidList;
    }

    public void setDsGroupPidList(String dsGroupPidList) {
        this.dsGroupPidList = dsGroupPidList == null ? null : dsGroupPidList.trim();
    }

    public Integer getDsGroupChildCount() {
        return dsGroupChildCount;
    }

    public void setDsGroupChildCount(Integer dsGroupChildCount) {
        this.dsGroupChildCount = dsGroupChildCount;
    }
}