package com.jbuild4d.base.dbaccess.dbentities.builder;

import com.jbuild4d.base.dbaccess.anno.DBKeyField;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TBUILD_DATASET_RELATED_TABLE
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class DatasetRelatedTableEntity {
    //RT_ID
    @DBKeyField
    private String rtId;

    //RT_DS_ID
    private String rtDsId;

    //RT_TABLE_NAME
    private String rtTableName;

    //RT_TABLE_CAPTION
    private String rtTableCaption;

    //RT_TABLE_ID
    private String rtTableId;

    //RT_TABLE_TYPE
    private String rtTableType;

    //RT_DESC
    private String rtDesc;

    //RT_ORDER_NUM
    private Integer rtOrderNum;

    public DatasetRelatedTableEntity(String rtId, String rtDsId, String rtTableName, String rtTableCaption, String rtTableId, String rtTableType, String rtDesc, Integer rtOrderNum) {
        this.rtId = rtId;
        this.rtDsId = rtDsId;
        this.rtTableName = rtTableName;
        this.rtTableCaption = rtTableCaption;
        this.rtTableId = rtTableId;
        this.rtTableType = rtTableType;
        this.rtDesc = rtDesc;
        this.rtOrderNum = rtOrderNum;
    }

    public DatasetRelatedTableEntity() {
        super();
    }

    public String getRtId() {
        return rtId;
    }

    public void setRtId(String rtId) {
        this.rtId = rtId == null ? null : rtId.trim();
    }

    public String getRtDsId() {
        return rtDsId;
    }

    public void setRtDsId(String rtDsId) {
        this.rtDsId = rtDsId == null ? null : rtDsId.trim();
    }

    public String getRtTableName() {
        return rtTableName;
    }

    public void setRtTableName(String rtTableName) {
        this.rtTableName = rtTableName == null ? null : rtTableName.trim();
    }

    public String getRtTableCaption() {
        return rtTableCaption;
    }

    public void setRtTableCaption(String rtTableCaption) {
        this.rtTableCaption = rtTableCaption == null ? null : rtTableCaption.trim();
    }

    public String getRtTableId() {
        return rtTableId;
    }

    public void setRtTableId(String rtTableId) {
        this.rtTableId = rtTableId == null ? null : rtTableId.trim();
    }

    public String getRtTableType() {
        return rtTableType;
    }

    public void setRtTableType(String rtTableType) {
        this.rtTableType = rtTableType == null ? null : rtTableType.trim();
    }

    public String getRtDesc() {
        return rtDesc;
    }

    public void setRtDesc(String rtDesc) {
        this.rtDesc = rtDesc == null ? null : rtDesc.trim();
    }

    public Integer getRtOrderNum() {
        return rtOrderNum;
    }

    public void setRtOrderNum(Integer rtOrderNum) {
        this.rtOrderNum = rtOrderNum;
    }
}