package com.jbuild4d.base.dbaccess.dbentities.builder;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.jbuild4d.base.dbaccess.anno.DBKeyField;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb4d_list_resource
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ListResourceEntity {
    //LIST_ID
    @DBKeyField
    private String listId;

    //LIST_CODE
    private String listCode;

    //LIST_NAME
    private String listName;

    //LIST_SINGLE_NAME
    private String listSingleName;

    //LIST_CREATE_TIME
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date listCreateTime;

    //LIST_CREATER
    private String listCreater;

    //LIST_UPDATE_TIME
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date listUpdateTime;

    //LIST_UPDATER
    private String listUpdater;

    //LIST_TYPE
    private String listType;

    //LIST_ISSYSTEM
    private String listIssystem;

    //LIST_ORDER_NUM
    private Integer listOrderNum;

    //LIST_DESC
    private String listDesc;

    //LIST_MODULE_ID
    private String listModuleId;

    //LIST_STATUS
    private String listStatus;

    //LIST_ORGAN_ID
    private String listOrganId;

    //LIST_ORGAN_NAME
    private String listOrganName;

    //LIST_DATASET_ID
    private String listDatasetId;

    public ListResourceEntity(String listId, String listCode, String listName, String listSingleName, Date listCreateTime, String listCreater, Date listUpdateTime, String listUpdater, String listType, String listIssystem, Integer listOrderNum, String listDesc, String listModuleId, String listStatus, String listOrganId, String listOrganName, String listDatasetId) {
        this.listId = listId;
        this.listCode = listCode;
        this.listName = listName;
        this.listSingleName = listSingleName;
        this.listCreateTime = listCreateTime;
        this.listCreater = listCreater;
        this.listUpdateTime = listUpdateTime;
        this.listUpdater = listUpdater;
        this.listType = listType;
        this.listIssystem = listIssystem;
        this.listOrderNum = listOrderNum;
        this.listDesc = listDesc;
        this.listModuleId = listModuleId;
        this.listStatus = listStatus;
        this.listOrganId = listOrganId;
        this.listOrganName = listOrganName;
        this.listDatasetId = listDatasetId;
    }

    public ListResourceEntity() {
        super();
    }

    public String getListId() {
        return listId;
    }

    public void setListId(String listId) {
        this.listId = listId == null ? null : listId.trim();
    }

    public String getListCode() {
        return listCode;
    }

    public void setListCode(String listCode) {
        this.listCode = listCode == null ? null : listCode.trim();
    }

    public String getListName() {
        return listName;
    }

    public void setListName(String listName) {
        this.listName = listName == null ? null : listName.trim();
    }

    public String getListSingleName() {
        return listSingleName;
    }

    public void setListSingleName(String listSingleName) {
        this.listSingleName = listSingleName == null ? null : listSingleName.trim();
    }

    public Date getListCreateTime() {
        return listCreateTime;
    }

    public void setListCreateTime(Date listCreateTime) {
        this.listCreateTime = listCreateTime;
    }

    public String getListCreater() {
        return listCreater;
    }

    public void setListCreater(String listCreater) {
        this.listCreater = listCreater == null ? null : listCreater.trim();
    }

    public Date getListUpdateTime() {
        return listUpdateTime;
    }

    public void setListUpdateTime(Date listUpdateTime) {
        this.listUpdateTime = listUpdateTime;
    }

    public String getListUpdater() {
        return listUpdater;
    }

    public void setListUpdater(String listUpdater) {
        this.listUpdater = listUpdater == null ? null : listUpdater.trim();
    }

    public String getListType() {
        return listType;
    }

    public void setListType(String listType) {
        this.listType = listType == null ? null : listType.trim();
    }

    public String getListIssystem() {
        return listIssystem;
    }

    public void setListIssystem(String listIssystem) {
        this.listIssystem = listIssystem == null ? null : listIssystem.trim();
    }

    public Integer getListOrderNum() {
        return listOrderNum;
    }

    public void setListOrderNum(Integer listOrderNum) {
        this.listOrderNum = listOrderNum;
    }

    public String getListDesc() {
        return listDesc;
    }

    public void setListDesc(String listDesc) {
        this.listDesc = listDesc == null ? null : listDesc.trim();
    }

    public String getListModuleId() {
        return listModuleId;
    }

    public void setListModuleId(String listModuleId) {
        this.listModuleId = listModuleId == null ? null : listModuleId.trim();
    }

    public String getListStatus() {
        return listStatus;
    }

    public void setListStatus(String listStatus) {
        this.listStatus = listStatus == null ? null : listStatus.trim();
    }

    public String getListOrganId() {
        return listOrganId;
    }

    public void setListOrganId(String listOrganId) {
        this.listOrganId = listOrganId == null ? null : listOrganId.trim();
    }

    public String getListOrganName() {
        return listOrganName;
    }

    public void setListOrganName(String listOrganName) {
        this.listOrganName = listOrganName == null ? null : listOrganName.trim();
    }

    public String getListDatasetId() {
        return listDatasetId;
    }

    public void setListDatasetId(String listDatasetId) {
        this.listDatasetId = listDatasetId == null ? null : listDatasetId.trim();
    }
}