package com.jbuild4d.base.dbaccess.dbentities.builder;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.jbuild4d.base.dbaccess.anno.DBKeyField;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb4d_service_link
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ServiceLinkEntity {
    //LINK_ID
    @DBKeyField
    private String linkId;

    //LINK_VALUE
    private String linkValue;

    //LINK_NAME
    private String linkName;

    //LINK_TYPE
    private String linkType;

    //LINK_URL
    private String linkUrl;

    //LINK_PARAS
    private String linkParas;

    //LINK_USER
    private String linkUser;

    //LINK_PASSWORD
    private String linkPassword;

    //LINK_CREATE_TIME
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date linkCreateTime;

    //LINK_ORDER_NUM
    private Integer linkOrderNum;

    //LINK_DESC
    private String linkDesc;

    //LINK_IS_LOCATION
    private String linkIsLocation;

    //LINK_STATUS
    private String linkStatus;

    public ServiceLinkEntity(String linkId, String linkValue, String linkName, String linkType, String linkUrl, String linkParas, String linkUser, String linkPassword, Date linkCreateTime, Integer linkOrderNum, String linkDesc, String linkIsLocation, String linkStatus) {
        this.linkId = linkId;
        this.linkValue = linkValue;
        this.linkName = linkName;
        this.linkType = linkType;
        this.linkUrl = linkUrl;
        this.linkParas = linkParas;
        this.linkUser = linkUser;
        this.linkPassword = linkPassword;
        this.linkCreateTime = linkCreateTime;
        this.linkOrderNum = linkOrderNum;
        this.linkDesc = linkDesc;
        this.linkIsLocation = linkIsLocation;
        this.linkStatus = linkStatus;
    }

    public ServiceLinkEntity() {
        super();
    }

    public String getLinkId() {
        return linkId;
    }

    public void setLinkId(String linkId) {
        this.linkId = linkId == null ? null : linkId.trim();
    }

    public String getLinkValue() {
        return linkValue;
    }

    public void setLinkValue(String linkValue) {
        this.linkValue = linkValue == null ? null : linkValue.trim();
    }

    public String getLinkName() {
        return linkName;
    }

    public void setLinkName(String linkName) {
        this.linkName = linkName == null ? null : linkName.trim();
    }

    public String getLinkType() {
        return linkType;
    }

    public void setLinkType(String linkType) {
        this.linkType = linkType == null ? null : linkType.trim();
    }

    public String getLinkUrl() {
        return linkUrl;
    }

    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl == null ? null : linkUrl.trim();
    }

    public String getLinkParas() {
        return linkParas;
    }

    public void setLinkParas(String linkParas) {
        this.linkParas = linkParas == null ? null : linkParas.trim();
    }

    public String getLinkUser() {
        return linkUser;
    }

    public void setLinkUser(String linkUser) {
        this.linkUser = linkUser == null ? null : linkUser.trim();
    }

    public String getLinkPassword() {
        return linkPassword;
    }

    public void setLinkPassword(String linkPassword) {
        this.linkPassword = linkPassword == null ? null : linkPassword.trim();
    }

    public Date getLinkCreateTime() {
        return linkCreateTime;
    }

    public void setLinkCreateTime(Date linkCreateTime) {
        this.linkCreateTime = linkCreateTime;
    }

    public Integer getLinkOrderNum() {
        return linkOrderNum;
    }

    public void setLinkOrderNum(Integer linkOrderNum) {
        this.linkOrderNum = linkOrderNum;
    }

    public String getLinkDesc() {
        return linkDesc;
    }

    public void setLinkDesc(String linkDesc) {
        this.linkDesc = linkDesc == null ? null : linkDesc.trim();
    }

    public String getLinkIsLocation() {
        return linkIsLocation;
    }

    public void setLinkIsLocation(String linkIsLocation) {
        this.linkIsLocation = linkIsLocation == null ? null : linkIsLocation.trim();
    }

    public String getLinkStatus() {
        return linkStatus;
    }

    public void setLinkStatus(String linkStatus) {
        this.linkStatus = linkStatus == null ? null : linkStatus.trim();
    }
}