package com.jbuild4d.base.dbaccess.dbentities.builder;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb4d_template_resource
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TemplateResourceEntityWithBLOBs extends TemplateResourceEntity {
    //TEMPLATE_IS_RESOLVE
    private String templateIsResolve;

    //TEMPLATE_HTML_SOURCE
    private String templateHtmlSource;

    //TEMPLATE_HTML_RESOLVE
    private String templateHtmlResolve;

    //TEMPLATE_JS_CONTENT
    private String templateJsContent;

    //TEMPLATE_CSS_CONTENT
    private String templateCssContent;

    //TEMPLATE_CONFIG_CONTENT
    private String templateConfigContent;

    public TemplateResourceEntityWithBLOBs(String templateId, String templateName, Date templateCreateTime, String templateCreater, Date templateUpdateTime, String templateUpdater, String templateType, String templateIssystem, Integer templateOrderNum, String templateDesc, String templateModuleId, String templateStatus, String templateOrganId, String templateOrganName, String templateIsTemplate, String templateContentUrl, String templateIsResolve, String templateHtmlSource, String templateHtmlResolve, String templateJsContent, String templateCssContent, String templateConfigContent) {
        super(templateId, templateName, templateCreateTime, templateCreater, templateUpdateTime, templateUpdater, templateType, templateIssystem, templateOrderNum, templateDesc, templateModuleId, templateStatus, templateOrganId, templateOrganName, templateIsTemplate, templateContentUrl);
        this.templateIsResolve = templateIsResolve;
        this.templateHtmlSource = templateHtmlSource;
        this.templateHtmlResolve = templateHtmlResolve;
        this.templateJsContent = templateJsContent;
        this.templateCssContent = templateCssContent;
        this.templateConfigContent = templateConfigContent;
    }

    public TemplateResourceEntityWithBLOBs() {
        super();
    }

    public String getTemplateIsResolve() {
        return templateIsResolve;
    }

    public void setTemplateIsResolve(String templateIsResolve) {
        this.templateIsResolve = templateIsResolve == null ? null : templateIsResolve.trim();
    }

    public String getTemplateHtmlSource() {
        return templateHtmlSource;
    }

    public void setTemplateHtmlSource(String templateHtmlSource) {
        this.templateHtmlSource = templateHtmlSource == null ? null : templateHtmlSource.trim();
    }

    public String getTemplateHtmlResolve() {
        return templateHtmlResolve;
    }

    public void setTemplateHtmlResolve(String templateHtmlResolve) {
        this.templateHtmlResolve = templateHtmlResolve == null ? null : templateHtmlResolve.trim();
    }

    public String getTemplateJsContent() {
        return templateJsContent;
    }

    public void setTemplateJsContent(String templateJsContent) {
        this.templateJsContent = templateJsContent == null ? null : templateJsContent.trim();
    }

    public String getTemplateCssContent() {
        return templateCssContent;
    }

    public void setTemplateCssContent(String templateCssContent) {
        this.templateCssContent = templateCssContent == null ? null : templateCssContent.trim();
    }

    public String getTemplateConfigContent() {
        return templateConfigContent;
    }

    public void setTemplateConfigContent(String templateConfigContent) {
        this.templateConfigContent = templateConfigContent == null ? null : templateConfigContent.trim();
    }
}