package com.jbuild4d.base.dbaccess.dbentities.builder;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb4d_template_resource
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TemplateResourceEntityWithBLOBs extends TemplateResourceEntity {
    //TEMPLATE_HTML_CONTENT
    private String templateHtmlContent;

    //TEMPLATE_JS_CONTENT
    private String templateJsContent;

    //TEMPLATE_CSS_CONTENT
    private String templateCssContent;

    //TEMPLATE_CONFIG_CONTENT
    private String templateConfigContent;

    public TemplateResourceEntityWithBLOBs(String templateId, String templateName, Date templateCreateTime, String templateCreater, Date templateUpdateTime, String templateUpdater, String templateType, String templateIssystem, Integer templateOrderNum, String templateDesc, String templateModuleId, String templateStatus, String templateOrganId, String templateOrganName, String templateIsTemplate, String templateContentUrl, String templateHtmlContent, String templateJsContent, String templateCssContent, String templateConfigContent) {
        super(templateId, templateName, templateCreateTime, templateCreater, templateUpdateTime, templateUpdater, templateType, templateIssystem, templateOrderNum, templateDesc, templateModuleId, templateStatus, templateOrganId, templateOrganName, templateIsTemplate, templateContentUrl);
        this.templateHtmlContent = templateHtmlContent;
        this.templateJsContent = templateJsContent;
        this.templateCssContent = templateCssContent;
        this.templateConfigContent = templateConfigContent;
    }

    public TemplateResourceEntityWithBLOBs() {
        super();
    }

    public String getTemplateHtmlContent() {
        return templateHtmlContent;
    }

    public void setTemplateHtmlContent(String templateHtmlContent) {
        this.templateHtmlContent = templateHtmlContent == null ? null : templateHtmlContent.trim();
    }

    public String getTemplateJsContent() {
        return templateJsContent;
    }

    public void setTemplateJsContent(String templateJsContent) {
        this.templateJsContent = templateJsContent == null ? null : templateJsContent.trim();
    }

    public String getTemplateCssContent() {
        return templateCssContent;
    }

    public void setTemplateCssContent(String templateCssContent) {
        this.templateCssContent = templateCssContent == null ? null : templateCssContent.trim();
    }

    public String getTemplateConfigContent() {
        return templateConfigContent;
    }

    public void setTemplateConfigContent(String templateConfigContent) {
        this.templateConfigContent = templateConfigContent == null ? null : templateConfigContent.trim();
    }
}