package com.jbuild4d.base.dbaccess.dbentities.system;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.jbuild4d.base.dbaccess.anno.DBKeyField;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TB4D_ORGAN
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class OrganEntity {
    //ORGAN_ID
    @DBKeyField
    private String organId;

    //ORGAN_NAME
    private String organName;

    //ORGAN_NO
    private String organNo;

    //ORGAN_CODE
    private String organCode;

    //ORGAN_CREATE_TIME
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date organCreateTime;

    //ORGAN_PHONE
    private String organPhone;

    //ORGAN_POST
    private String organPost;

    //ORGAN_TYPE_VALUE
    private String organTypeValue;

    //ORGAN_ADDRESS
    private String organAddress;

    //ORGAN_CONTACTOR
    private String organContactor;

    //ORGAN_CONTACTOR_MOBILE
    private String organContactorMobile;

    //ORGAN_DOMAIN
    private String organDomain;

    //ORGAN_FAX
    private String organFax;

    //ORGAN_CHILD_COUNT
    private Integer organChildCount;

    //ORGAN_IS_VIRTUAL
    private String organIsVirtual;

    //ORGAN_ORDER_NUM
    private Integer organOrderNum;

    //ORGAN_PARENT_ID
    private String organParentId;

    //ORGAN_PARENT_ID_LIST
    private String organParentIdList;

    //ORGAN_SHORT_NAME
    private String organShortName;

    //ORGAN_STATUS
    private String organStatus;

    //ORGAN_CREATRE_ORG_ID
    private String organCreatreOrgId;

    //ORGAN_OUTER_ID
    private String organOuterId;

    //ORGAN_OUTER_TYPE
    private String organOuterType;

    public OrganEntity(String organId, String organName, String organNo, String organCode, Date organCreateTime, String organPhone, String organPost, String organTypeValue, String organAddress, String organContactor, String organContactorMobile, String organDomain, String organFax, Integer organChildCount, String organIsVirtual, Integer organOrderNum, String organParentId, String organParentIdList, String organShortName, String organStatus, String organCreatreOrgId, String organOuterId, String organOuterType) {
        this.organId = organId;
        this.organName = organName;
        this.organNo = organNo;
        this.organCode = organCode;
        this.organCreateTime = organCreateTime;
        this.organPhone = organPhone;
        this.organPost = organPost;
        this.organTypeValue = organTypeValue;
        this.organAddress = organAddress;
        this.organContactor = organContactor;
        this.organContactorMobile = organContactorMobile;
        this.organDomain = organDomain;
        this.organFax = organFax;
        this.organChildCount = organChildCount;
        this.organIsVirtual = organIsVirtual;
        this.organOrderNum = organOrderNum;
        this.organParentId = organParentId;
        this.organParentIdList = organParentIdList;
        this.organShortName = organShortName;
        this.organStatus = organStatus;
        this.organCreatreOrgId = organCreatreOrgId;
        this.organOuterId = organOuterId;
        this.organOuterType = organOuterType;
    }

    public OrganEntity() {
        super();
    }

    public String getOrganId() {
        return organId;
    }

    public void setOrganId(String organId) {
        this.organId = organId == null ? null : organId.trim();
    }

    public String getOrganName() {
        return organName;
    }

    public void setOrganName(String organName) {
        this.organName = organName == null ? null : organName.trim();
    }

    public String getOrganNo() {
        return organNo;
    }

    public void setOrganNo(String organNo) {
        this.organNo = organNo == null ? null : organNo.trim();
    }

    public String getOrganCode() {
        return organCode;
    }

    public void setOrganCode(String organCode) {
        this.organCode = organCode == null ? null : organCode.trim();
    }

    public Date getOrganCreateTime() {
        return organCreateTime;
    }

    public void setOrganCreateTime(Date organCreateTime) {
        this.organCreateTime = organCreateTime;
    }

    public String getOrganPhone() {
        return organPhone;
    }

    public void setOrganPhone(String organPhone) {
        this.organPhone = organPhone == null ? null : organPhone.trim();
    }

    public String getOrganPost() {
        return organPost;
    }

    public void setOrganPost(String organPost) {
        this.organPost = organPost == null ? null : organPost.trim();
    }

    public String getOrganTypeValue() {
        return organTypeValue;
    }

    public void setOrganTypeValue(String organTypeValue) {
        this.organTypeValue = organTypeValue == null ? null : organTypeValue.trim();
    }

    public String getOrganAddress() {
        return organAddress;
    }

    public void setOrganAddress(String organAddress) {
        this.organAddress = organAddress == null ? null : organAddress.trim();
    }

    public String getOrganContactor() {
        return organContactor;
    }

    public void setOrganContactor(String organContactor) {
        this.organContactor = organContactor == null ? null : organContactor.trim();
    }

    public String getOrganContactorMobile() {
        return organContactorMobile;
    }

    public void setOrganContactorMobile(String organContactorMobile) {
        this.organContactorMobile = organContactorMobile == null ? null : organContactorMobile.trim();
    }

    public String getOrganDomain() {
        return organDomain;
    }

    public void setOrganDomain(String organDomain) {
        this.organDomain = organDomain == null ? null : organDomain.trim();
    }

    public String getOrganFax() {
        return organFax;
    }

    public void setOrganFax(String organFax) {
        this.organFax = organFax == null ? null : organFax.trim();
    }

    public Integer getOrganChildCount() {
        return organChildCount;
    }

    public void setOrganChildCount(Integer organChildCount) {
        this.organChildCount = organChildCount;
    }

    public String getOrganIsVirtual() {
        return organIsVirtual;
    }

    public void setOrganIsVirtual(String organIsVirtual) {
        this.organIsVirtual = organIsVirtual == null ? null : organIsVirtual.trim();
    }

    public Integer getOrganOrderNum() {
        return organOrderNum;
    }

    public void setOrganOrderNum(Integer organOrderNum) {
        this.organOrderNum = organOrderNum;
    }

    public String getOrganParentId() {
        return organParentId;
    }

    public void setOrganParentId(String organParentId) {
        this.organParentId = organParentId == null ? null : organParentId.trim();
    }

    public String getOrganParentIdList() {
        return organParentIdList;
    }

    public void setOrganParentIdList(String organParentIdList) {
        this.organParentIdList = organParentIdList == null ? null : organParentIdList.trim();
    }

    public String getOrganShortName() {
        return organShortName;
    }

    public void setOrganShortName(String organShortName) {
        this.organShortName = organShortName == null ? null : organShortName.trim();
    }

    public String getOrganStatus() {
        return organStatus;
    }

    public void setOrganStatus(String organStatus) {
        this.organStatus = organStatus == null ? null : organStatus.trim();
    }

    public String getOrganCreatreOrgId() {
        return organCreatreOrgId;
    }

    public void setOrganCreatreOrgId(String organCreatreOrgId) {
        this.organCreatreOrgId = organCreatreOrgId == null ? null : organCreatreOrgId.trim();
    }

    public String getOrganOuterId() {
        return organOuterId;
    }

    public void setOrganOuterId(String organOuterId) {
        this.organOuterId = organOuterId == null ? null : organOuterId.trim();
    }

    public String getOrganOuterType() {
        return organOuterType;
    }

    public void setOrganOuterType(String organOuterType) {
        this.organOuterType = organOuterType == null ? null : organOuterType.trim();
    }
}