
-----------------------------------------初始化文件夹-----------------------------------------
INSERT INTO
  TB4D_MENU (FOLDER_ID, FOLDER_NAME, FOLDER_TEXT, FOLDER_VALUE, FOLDER_TYPE, IS_EXPAND, IS_SYSTEM, LEFT_URL, RIGHT_URL, ORDER_ID, ORGAN_ID, PARENT_ID, PARENT_ID_LIST, ICON_CLASS_NAME, CHILD_COUNT)
VALUES (0, 'Root', 'Root', 'Root', 'Group', '1', '1', '', '', 1, '0', '-1', '-1*0', '', 1)

INSERT INTO
  TB4D_MENU (FOLDER_ID, FOLDER_NAME, FOLDER_TEXT, FOLDER_VALUE, FOLDER_TYPE, IS_EXPAND, IS_SYSTEM, LEFT_URL, RIGHT_URL, ORDER_ID, ORGAN_ID, PARENT_ID, PARENT_ID_LIST, ICON_CLASS_NAME, CHILD_COUNT)
VALUES (100000, '应用管理', '应用管理', '应用管理', 'Group', '1', '1', '', '', 2, '0', '0', '-1*0*100000', '', 1)

INSERT INTO
  TB4D_MENU (FOLDER_ID, FOLDER_NAME, FOLDER_TEXT, FOLDER_VALUE, FOLDER_TYPE, IS_EXPAND, IS_SYSTEM, LEFT_URL, RIGHT_URL, ORDER_ID, ORGAN_ID, PARENT_ID, PARENT_ID_LIST, ICON_CLASS_NAME, CHILD_COUNT)
VALUES (100100, '存储管理', '存储管理', '存储管理', 'Group', '1', '1', '', '', 3, '0', '100000', '-1*0*100000*100100', '', 1)

INSERT INTO
  TB4D_MENU (FOLDER_ID, FOLDER_NAME, FOLDER_TEXT, FOLDER_VALUE, FOLDER_TYPE, IS_EXPAND, IS_SYSTEM, LEFT_URL, RIGHT_URL, ORDER_ID, ORGAN_ID, PARENT_ID, PARENT_ID_LIST, ICON_CLASS_NAME, CHILD_COUNT)
VALUES (100200, '数据集管理', '数据集管理', '数据集管理', 'Group', '1', '1', '', '', 4, '0', '100000', '-1*0*100000*100200', '', 1)

INSERT INTO
  TB4D_MENU (FOLDER_ID, FOLDER_NAME, FOLDER_TEXT, FOLDER_VALUE, FOLDER_TYPE, IS_EXPAND, IS_SYSTEM, LEFT_URL, RIGHT_URL, ORDER_ID, ORGAN_ID, PARENT_ID, PARENT_ID_LIST, ICON_CLASS_NAME, CHILD_COUNT)
VALUES (100300, '模块管理', '模块管理', '模块管理', 'Group', '1', '1', '', '', 4, '0', '100000', '-1*0*100000*100300', '', 1)